workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_pro
    environment:
      flutter: stable
      xcode: 13.3.1
      cocoapods: default
    scripts:
      - name: Build test package
        script: |
          flutter build ios integration_test/app_test.dart --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -config Flutter/Runner.xcworkspace -derivedDataPath ./build/ios_integ -sdk iphonesimulator build-for-testing 
          cd build/ios_integ/Build/Products
          zip -r "ios_tests.zip" "Release-iphoneos" "Runner_iphoneos15.4-arm64.xctestrun"
      - name: Run Firebase Test Lab tests
        script: |
          echo $GCLOUD_KEY_FILE > ./gcloud_key_file.json
          gcloud auth activate-service-account --key-file=gcloud_key_file.json
          gcloud --quiet config set project $FIREBASE_PROJECT 
          gcloud firebase test ios run --test "/Users/builder/clone/ios/build/ios_integ/Build/Products/ios_tests.zip" \
            --device model=iphone11pro,version=14.7,locale=en_US,orientation=portrait \
            --xcode-version=13.3.1 \
            --timeout 10m

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - /Users/builder/clone/ios/build/ios_integ/Build/Products/ios_tests.zip
